package ${package};

import com.github.farzadsedaghatbin.shipflow.plugin.RiskCalculatorPlugin;
import java.util.Map;
import org.springframework.stereotype.Component;

/**
 * Example ShipFlow risk calculator plugin, generated by shipflow-plugin-archetype.
 *
 * <p>Implement {@link RiskCalculatorPlugin#calculateRisk(Map)} with your own logic, or delete
 * this class and implement {@code ReportGeneratorPlugin} or {@code IntegrationProviderPlugin}
 * instead — see the SPI interfaces in the {@code shipflow-plugin-api} dependency.
 *
 * <p>Once this project is built and added as a dependency of the ShipFlow backend build (see
 * plugin-sdk/README.md — "Deployment"), Spring auto-discovers this {@code @Component} and
 * {@code PluginAutoConfiguration} registers it automatically on startup. It then appears in
 * Organization Settings → Plugins, where an ADMIN can enable/disable it at runtime.
 */
@Component
public class SampleRiskCalculatorPlugin implements RiskCalculatorPlugin {

  @Override
  public String getPluginId() {
    return "${artifactId}-sample-risk";
  }

  @Override
  public String getDisplayName() {
    return "Sample Risk Calculator (${artifactId})";
  }

  @Override
  public Double calculateRisk(Map<String, Object> context) {
    // context keys: pitchId, pitchTitle, appetiteDays, cycleId,
    //               taskCount, completedTaskCount, daysRemaining
    Integer daysRemaining = (Integer) context.get("daysRemaining");
    Integer taskCount = (Integer) context.get("taskCount");
    Integer completedTaskCount = (Integer) context.get("completedTaskCount");

    if (taskCount == null || taskCount == 0) {
      return null; // abstain — not enough data to score this pitch
    }

    double progress = completedTaskCount == null ? 0.0 : (double) completedTaskCount / taskCount;
    // Return null to abstain; return a value in [0.0, 1.0] to vote on risk.
    return daysRemaining != null && daysRemaining < 7 && progress < 0.5 ? 0.9 : 0.2;
  }
}
