ALTER TABLE work_log_timers ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'RUNNING';
ALTER TABLE work_log_timers ADD COLUMN IF NOT EXISTS paused_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE work_log_timers ADD COLUMN IF NOT EXISTS total_paused_seconds BIGINT DEFAULT 0;
