-- V29: Add dashboard widgets and notifications
-- This migration adds support for customizable dashboard widgets and notifications

-- Dashboard Widgets table
CREATE TABLE dashboard_widgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    widget_type VARCHAR(50) NOT NULL,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    layout_config TEXT,
    settings TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE (user_id, widget_type)
);

CREATE INDEX idx_widget_user ON dashboard_widgets(user_id);
CREATE INDEX idx_widget_order ON dashboard_widgets(user_id, display_order);

-- Dashboard Notifications table
CREATE TABLE dashboard_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    severity VARCHAR(20) NOT NULL DEFAULT 'INFO',
    action_url VARCHAR(500),
    entity_type VARCHAR(50),
    entity_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP NULL,
    expires_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_user ON dashboard_notifications(user_id);
CREATE INDEX idx_notification_read ON dashboard_notifications(is_read);
CREATE INDEX idx_notification_created ON dashboard_notifications(created_at);
CREATE INDEX idx_notification_type ON dashboard_notifications(user_id, type);
CREATE INDEX idx_notification_entity ON dashboard_notifications(entity_type, entity_id);

-- Create default widgets for existing users
-- Note: These will be created by the application when users first access the dashboard
-- Keeping migration simple to avoid circular dependencies
