#!/usr/bin/env node
/**
 * Generates `dist/sitemap.xml` from the real route list and the blog index.
 *
 * The sitemap used to be hand-maintained in `public/sitemap.xml`. It drifted:
 * `lastmod` dates froze months behind reality and a published post
 * (`what-is-shape-up`) was never added, so Google was never told it existed.
 * Generating it at build time from `public/blog/index.json` and each post's
 * frontmatter removes that whole class of mistake.
 *
 * Run automatically by `npm run build`.
 *
 * To add a static page: add it to STATIC_ROUTES below.
 * To add a blog post: drop the `.md` in `public/blog/posts/` and add its slug
 * to `public/blog/index.json` — the sitemap picks it up with no edit here.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PUBLIC_DIR = join(ROOT, 'public');
const DIST_DIR = join(ROOT, 'dist');
const SITE_URL = 'https://shipflow.dev';

/**
 * Public, indexable routes. Keep in sync with the public routes in
 * `src/App.tsx`. `/login` is deliberately absent — it is served with
 * `noindex`, so listing it would ask Google to index a page that refuses.
 */
const STATIC_ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/blog', changefreq: 'weekly', priority: '0.9' },
  { path: '/compare', changefreq: 'monthly', priority: '0.8' },
  { path: '/public-roadmap', changefreq: 'weekly', priority: '0.7' },
  { path: '/releases', changefreq: 'monthly', priority: '0.7' },
];

/** Extracts a `key: value` line from a markdown frontmatter block. */
function frontmatterValue(raw, key) {
  const fence = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!fence) return null;
  for (const line of fence[1].split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    if (line.slice(0, idx).trim() !== key) continue;
    return line
      .slice(idx + 1)
      .trim()
      .replace(/^["']|["']$/g, '');
  }
  return null;
}

function isoDate(value) {
  if (!value) return null;
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
}

function xmlEscape(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function collectBlogRoutes() {
  const indexPath = join(PUBLIC_DIR, 'blog', 'index.json');
  if (!existsSync(indexPath)) {
    console.warn('[sitemap] no blog/index.json found — skipping blog routes');
    return [];
  }

  const slugs = JSON.parse(readFileSync(indexPath, 'utf8'));
  const routes = [];

  for (const slug of slugs) {
    const postPath = join(PUBLIC_DIR, 'blog', 'posts', `${slug}.md`);
    if (!existsSync(postPath)) {
      // A slug in the index with no file behind it would become a 404 in the
      // sitemap, which Google reports as a crawl error against the whole site.
      console.warn(`[sitemap] index.json lists "${slug}" but ${slug}.md is missing — skipped`);
      continue;
    }
    const raw = readFileSync(postPath, 'utf8');
    routes.push({
      path: `/blog/${slug}`,
      lastmod: isoDate(frontmatterValue(raw, 'date')),
      changefreq: 'monthly',
      priority: '0.9',
    });
  }

  return routes;
}

function buildSitemap(routes) {
  const today = new Date().toISOString().slice(0, 10);
  const entries = routes
    .map((r) => {
      const lastmod = r.lastmod ?? today;
      return [
        '  <url>',
        `    <loc>${xmlEscape(SITE_URL + r.path)}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${r.changefreq}</changefreq>`,
        `    <priority>${r.priority}</priority>`,
        '  </url>',
      ].join('\n');
    })
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries,
    '</urlset>',
    '',
  ].join('\n');
}

const blogRoutes = collectBlogRoutes();
const allRoutes = [...STATIC_ROUTES, ...blogRoutes];
const xml = buildSitemap(allRoutes);

const outDir = existsSync(DIST_DIR) ? DIST_DIR : PUBLIC_DIR;
const outPath = join(outDir, 'sitemap.xml');
writeFileSync(outPath, xml, 'utf8');

console.log(
  `[sitemap] wrote ${allRoutes.length} URLs (${STATIC_ROUTES.length} static, ${blogRoutes.length} posts) to ${outPath}`,
);
