package com.github.farzadsedaghatbin.shipflow.entity;

import com.github.farzadsedaghatbin.shipflow.entity.enums.QAFeedbackType;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import lombok.*;

/**
 * Entity for storing Q&A interactions and user feedback. Validated Q&A entries
 * can be re-embedded as additional knowledge.
 */
@Entity
@Table(name = "qa_interactions", indexes = {@Index(name = "idx_qa_user", columnList = "userId"),
    @Index(name = "idx_qa_context", columnList = "contextType, contextId"),
    @Index(name = "idx_qa_created", columnList = "createdAt")})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class QAInteraction {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** The question asked by the user. */
  @Column(columnDefinition = "TEXT", nullable = false)
  private String question;

  /** The answer generated by the AI. */
  @Column(columnDefinition = "TEXT")
  private String answer;

  /**
   * Context type (pitch, meeting, team, cycle) - where the question was asked
   * from.
   */
  @Column(length = 50)
  private String contextType;

  /** ID of the context entity. */
  private Long contextId;

  /** ID of the associated cycle. */
  private Long cycleId;

  /** ID of the associated team. */
  private Long teamId;

  /** ID of the user who asked the question. */
  @Column(nullable = false)
  private Long userId;

  /** Comma-separated list of knowledge item IDs used to generate the answer. */
  @Column(length = 500)
  private String sourceKnowledgeIds;

  /** AI confidence score (0-100). */
  private Integer confidenceScore;

  /** User feedback on the answer quality. */
  @Enumerated(EnumType.STRING)
  private QAFeedbackType feedbackType;

  /** User's correction or additional notes. */
  @Column(columnDefinition = "TEXT")
  private String feedbackCorrection;

  /** Simple helpful/unhelpful feedback for active learning. */
  private Boolean feedbackHelpful;

  /** Additional feedback text for active learning. */
  @Column(columnDefinition = "TEXT")
  private String feedbackText;

  /** Whether this validated Q&A has been embedded as knowledge. */
  @Builder.Default
  @Column(nullable = false)
  private Boolean isEmbedded = false;

  /** Processing time in milliseconds for the answer generation. */
  private Long processingTimeMs;

  @Column(nullable = false)
  private LocalDateTime createdAt;

  private LocalDateTime feedbackAt;

  @PrePersist
  protected void onCreate() {
    createdAt = LocalDateTime.now();
  }
}
