package com.github.farzadsedaghatbin.shipflow.controller;

import com.github.farzadsedaghatbin.shipflow.dto.pitch.PitchWriterRequestDTO;
import com.github.farzadsedaghatbin.shipflow.dto.pitch.PitchWriterResponseDTO;
import com.github.farzadsedaghatbin.shipflow.service.AIPitchWriterService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST controller for the AI Pitch Writer feature.
 *
 * <p>Endpoints:
 *
 * <ul>
 *   <li>{@code POST /api/ai/pitch-writer/generate} — generate a Shape Up pitch draft via LLM
 *   <li>{@code GET /api/ai/pitch-writer/status} — probe whether the AI backend is available
 * </ul>
 */
@RestController
@RequestMapping("/api/ai/pitch-writer")
@RequiredArgsConstructor
@Tag(name = "AI Pitch Writer", description = "Generate Shape Up pitch drafts using an LLM")
public class AIPitchWriterController {

  private final AIPitchWriterService pitchWriterService;

  /**
   * Generate a fully structured Shape Up pitch draft from a problem description.
   *
   * <p>Allowed roles: ADMIN, MANAGER, MEMBER (all authenticated users who can use AI features).
   */
  @PostMapping("/generate")
  @Operation(
      summary = "Generate a Shape Up pitch draft",
      description =
          "Accepts a problem description and optional hints; returns a fully structured"
              + " Shape Up pitch draft generated by the configured LLM.")
  @PreAuthorize("@permissionService.hasPermission('AI_FEATURES', 'EXECUTE')")
  public ResponseEntity<PitchWriterResponseDTO> generate(
      @Valid @RequestBody PitchWriterRequestDTO request) {
    PitchWriterResponseDTO response = pitchWriterService.generatePitch(request);
    return ResponseEntity.ok(response);
  }

  /**
   * Probe endpoint — returns whether the AI backend is configured and available.
   *
   * <p>No authentication required so that the frontend can conditionally show the AI Pitch Writer
   * button without a separate auth check.
   */
  @GetMapping("/status")
  @Operation(
      summary = "Check AI Pitch Writer availability",
      description =
          "Returns {\"available\": true} when an LLM provider is configured, false otherwise."
              + " No authentication required.")
  @PreAuthorize("permitAll()")
  public ResponseEntity<Map<String, Boolean>> status() {
    return ResponseEntity.ok(Map.of("available", pitchWriterService.isAvailable()));
  }
}
