package com.github.farzadsedaghatbin.shipflow.plugin.builtin;

import com.github.farzadsedaghatbin.shipflow.plugin.ReportGeneratorPlugin;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import org.springframework.stereotype.Component;

/**
 * Built-in report generator: produces a plain-text cycle health summary.
 * Always active — can be disabled via the admin Plugins page.
 */
@Component
public class CycleHealthReportPlugin implements ReportGeneratorPlugin {

  @Override
  public String getPluginId() {
    return "builtin-cycle-health-report";
  }

  @Override
  public String getDisplayName() {
    return "Cycle Health Summary Report";
  }

  @Override
  public String getContentType() {
    return "text/plain";
  }

  @Override
  public String getFileExtension() {
    return "txt";
  }

  @Override
  public byte[] generate(Map<String, Object> context) {
    Long projectId = context.containsKey("projectId") ? ((Number) context.get("projectId")).longValue() : null;
    Long cycleId = context.containsKey("cycleId") ? ((Number) context.get("cycleId")).longValue() : null;

    String report = String.format(
        "ShipFlow — Cycle Health Report%n"
            + "Project: %s%n"
            + "Cycle:   %s%n"
            + "%n"
            + "This report is generated by the built-in Cycle Health Report plugin.%n"
            + "Configure a report generator plugin to produce custom formats.%n",
        projectId != null ? projectId : "N/A",
        cycleId != null ? cycleId : "N/A");

    return report.getBytes(StandardCharsets.UTF_8);
  }
}
