package com.github.farzadsedaghatbin.shipflow.service.wisearchitecture;

import com.github.farzadsedaghatbin.shipflow.dto.wisearchitecture.GeneratedMarkdownFile;
import com.github.farzadsedaghatbin.shipflow.dto.wisearchitecture.StackSolutionDTO;
import com.github.farzadsedaghatbin.shipflow.dto.wisearchitecture.TechStackType;
import com.github.farzadsedaghatbin.shipflow.dto.wisearchitecture.WiseArchitectureResponseDTO;
import com.github.farzadsedaghatbin.shipflow.entity.Pitch;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * Generates agent-consumable Markdown files from a Wise Architecture solution.
 *
 * <p>Output files per analysis run:
 * <ol>
 *   <li>{@code architecture-overview.md} — Problem, appetite, stack summary, context sources.</li>
 *   <li>{@code {stack-id}-implementation-guide.md} — Full per-stack guide with components,
 *       API contracts, data model, reusable services, libraries, and implementation steps.</li>
 *   <li>{@code api-design.md} — Consolidated REST API contracts across all stacks (omitted when
 *       no stack defines API contracts).</li>
 *   <li>{@code implementation-plan.md} — Combined step-by-step implementation plan across all stacks.</li>
 * </ol>
 *
 * <p>These files are intended to be placed in a repository (e.g. {@code .wise/} directory) so that
 * AI coding agents (Claude Code, Cursor, GitHub Copilot Workspace) can read them and drive
 * implementation without any additional context.
 */
@Service
@Slf4j
public class WiseArchitectureMarkdownService {

    private static final DateTimeFormatter DT_FMT =
        DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    // ──────────────────────────────────────────────────────────────────────────────────────────────
    // Public API
    // ──────────────────────────────────────────────────────────────────────────────────────────────

    /**
     * Generate all Markdown files for a completed analysis.
     *
     * @param response the full analysis response
     * @param pitch    the pitch this analysis was run for
     * @return list of generated files (never null, may be empty on error)
     */
    public List<GeneratedMarkdownFile> generateFiles(
            WiseArchitectureResponseDTO response, Pitch pitch) {

        List<GeneratedMarkdownFile> files = new ArrayList<>();

        try {
            files.add(buildOverviewFile(response, pitch));

            for (Map.Entry<TechStackType, StackSolutionDTO> entry :
                    response.getSolutions().entrySet()) {
                files.add(buildStackGuideFile(entry.getKey(), entry.getValue(), pitch));
            }

            GeneratedMarkdownFile apiFile = buildApiDesignFile(response, pitch);
            if (apiFile != null) {
                files.add(apiFile);
            }

            files.add(buildImplementationPlanFile(response, pitch));

        } catch (Exception e) {
            log.error("Failed to generate markdown files for pitch {}: {}",
                pitch.getId(), e.getMessage(), e);
        }

        return files;
    }

    // ──────────────────────────────────────────────────────────────────────────────────────────────
    // File builders
    // ──────────────────────────────────────────────────────────────────────────────────────────────

    private GeneratedMarkdownFile buildOverviewFile(
            WiseArchitectureResponseDTO r, Pitch pitch) {

        StringBuilder md = new StringBuilder();
        md.append("# Architecture Overview: ").append(pitch.getTitle()).append("\n\n");

        md.append("> Generated by Wise Architecture on ")
          .append(r.getGeneratedAt() != null ? r.getGeneratedAt().format(DT_FMT) : "N/A")
          .append("\n\n");

        // Problem & solution
        if (pitch.getProblemStatement() != null && !pitch.getProblemStatement().isBlank()) {
            md.append("## Problem Statement\n\n")
              .append(pitch.getProblemStatement().strip()).append("\n\n");
        }
        if (pitch.getSolution() != null && !pitch.getSolution().isBlank()) {
            md.append("## Proposed Solution\n\n")
              .append(pitch.getSolution().strip()).append("\n\n");
        }

        // Appetite
        if (pitch.getAppetiteDays() != null) {
            int days = pitch.getAppetiteDays();
            int weeks = (int) Math.ceil(days / 5.0);
            int hours = days * 8;
            md.append("## Appetite\n\n")
              .append("**").append(weeks).append(" week")
              .append(weeks == 1 ? "" : "s").append("** (")
              .append(days).append(" days / ~")
              .append(hours).append(" hours)\n\n");
        }

        // Appetite check
        if (r.getAppetiteCheck() != null) {
            var ac = r.getAppetiteCheck();
            String status = Boolean.TRUE.equals(ac.getPassed()) ? "✅ Passed" : "⚠️ Exceeded";
            md.append("## Appetite Check\n\n")
              .append("**Status**: ").append(status).append("\n\n")
              .append("| | Hours |\n")
              .append("|---|---|\n")
              .append("| Estimated | **").append(ac.getEstimatedHours()).append("h** |\n")
              .append("| Available | **").append(ac.getAvailableHours()).append("h** |\n\n");

            if (ac.getMessage() != null) {
                md.append(ac.getMessage()).append("\n\n");
            }
        }

        // Reduced scope
        if (r.getReducedScope() != null) {
            var rs = r.getReducedScope();
            md.append("## Reduced Scope Suggestion\n\n")
              .append(rs.getExplanation()).append("\n\n");
            if (rs.getDeferredItems() != null && !rs.getDeferredItems().isEmpty()) {
                md.append("**Deferred items:**\n\n");
                rs.getDeferredItems().forEach(item ->
                    md.append("- ").append(item).append("\n"));
                md.append("\n");
            }
        }

        // Stack summary table
        if (r.getSolutions() != null && !r.getSolutions().isEmpty()) {
            md.append("## Technology Stacks\n\n")
              .append("| Stack | Estimated Hours | Guide File |\n")
              .append("|-------|----------------|------------|\n");
            r.getSolutions().forEach((stack, sol) -> {
                String hours = sol.getEstimatedHours() != null
                    ? sol.getEstimatedHours() + "h" : "—";
                md.append("| ").append(stack.getDisplayName())
                  .append(" | ").append(hours)
                  .append(" | [").append(stackGuideFilename(stack)).append("]")
                  .append("(./").append(stackGuideFilename(stack)).append(") |\n");
            });
            md.append("\n");
        }

        // Context sources
        if (r.getContextSources() != null) {
            var cs = r.getContextSources();
            md.append("## Context Sources\n\n")
              .append("| Source | Available |\n")
              .append("|--------|----------|\n")
              .append("| Code Repository (GitHub) | ")
              .append(Boolean.TRUE.equals(cs.getHasCodeContext()) ? "✅" : "❌").append(" |\n")
              .append("| Team Skills | ")
              .append(Boolean.TRUE.equals(cs.getHasTeamSkills()) ? "✅" : "❌").append(" |\n")
              .append("| Figma Design | ")
              .append(Boolean.TRUE.equals(cs.getHasFigmaContext()) ? "✅" : "❌").append(" |\n")
              .append("| Roadmap / Epic | ")
              .append(Boolean.TRUE.equals(cs.getHasRoadmapContext()) ? "✅" : "❌").append(" |\n\n");

            if (cs.getWarnings() != null && !cs.getWarnings().isEmpty()) {
                md.append("> **Note:** Some context sources were unavailable. "
                    + "The following may reduce accuracy:\n>\n");
                cs.getWarnings().forEach(w -> md.append("> - ").append(w).append("\n"));
                md.append("\n");
            }
        }

        // File index
        md.append("## Related Files\n\n")
          .append("- [API Design Guide](./api-design.md)\n")
          .append("- [Implementation Plan](./implementation-plan.md)\n");
        if (r.getSolutions() != null) {
            r.getSolutions().keySet().forEach(stack ->
                md.append("- [").append(stack.getDisplayName())
                  .append(" Guide](./").append(stackGuideFilename(stack)).append(")\n"));
        }

        return GeneratedMarkdownFile.builder()
            .filename("architecture-overview.md")
            .title("Architecture Overview")
            .content(md.toString())
            .category("overview")
            .stackType(null)
            .build();
    }

    private GeneratedMarkdownFile buildStackGuideFile(
            TechStackType stack, StackSolutionDTO sol, Pitch pitch) {

        StringBuilder md = new StringBuilder();
        md.append("# ").append(stack.getDisplayName())
          .append(" Implementation Guide\n\n");
        md.append("> **Pitch**: ").append(pitch.getTitle()).append("\n\n");
        md.append("> Read [architecture-overview.md](./architecture-overview.md) first "
                + "for problem context and appetite information.\n\n");

        // Architecture summary
        String summary = null;
        if (sol.getArchitectureDetail() != null && sol.getArchitectureDetail().getSummary() != null) {
            summary = sol.getArchitectureDetail().getSummary();
        } else if (sol.getArchitectureOverview() != null) {
            summary = sol.getArchitectureOverview();
        }
        if (summary != null && !summary.isBlank()) {
            md.append("## Architecture Summary\n\n").append(summary.strip()).append("\n\n");
        }

        // Components
        if (sol.getArchitectureDetail() != null
                && sol.getArchitectureDetail().getComponents() != null
                && !sol.getArchitectureDetail().getComponents().isEmpty()) {
            md.append("## Components\n\n");
            sol.getArchitectureDetail().getComponents().forEach(comp -> {
                md.append("### ").append(comp.getName()).append("\n\n");
                md.append("**Responsibility**: ").append(comp.getResponsibility()).append("\n\n");
                if (comp.getInteractsWith() != null && !comp.getInteractsWith().isEmpty()) {
                    md.append("**Interacts with**: ")
                      .append(String.join(", ", comp.getInteractsWith())).append("\n\n");
                }
            });
        }

        // API contracts
        if (sol.getArchitectureDetail() != null
                && sol.getArchitectureDetail().getApiContracts() != null
                && !sol.getArchitectureDetail().getApiContracts().isEmpty()) {
            md.append("## API Contracts\n\n")
              .append("| Method | Endpoint | Description |\n")
              .append("|--------|----------|-------------|\n");
            sol.getArchitectureDetail().getApiContracts().forEach(api ->
                md.append("| `").append(api.getMethod()).append("` | `")
                  .append(api.getEndpoint()).append("` | ")
                  .append(api.getDescription()).append(" |\n"));
            md.append("\n");

            sol.getArchitectureDetail().getApiContracts().forEach(api -> {
                md.append("### `").append(api.getMethod()).append(" ").append(api.getEndpoint())
                  .append("`\n\n");
                if (api.getDescription() != null) {
                    md.append(api.getDescription()).append("\n\n");
                }
                if (api.getRequestShape() != null && !api.getRequestShape().isBlank()) {
                    md.append("**Request**\n\n```json\n")
                      .append(api.getRequestShape()).append("\n```\n\n");
                }
                if (api.getResponseShape() != null && !api.getResponseShape().isBlank()) {
                    md.append("**Response**\n\n```json\n")
                      .append(api.getResponseShape()).append("\n```\n\n");
                }
            });
        }

        // Data model
        if (sol.getArchitectureDetail() != null
                && sol.getArchitectureDetail().getDataModel() != null
                && !sol.getArchitectureDetail().getDataModel().isEmpty()) {
            md.append("## Data Model\n\n");
            sol.getArchitectureDetail().getDataModel().forEach(entity -> {
                md.append("### ").append(entity.getEntityName()).append("\n\n");
                if (entity.getFields() != null && !entity.getFields().isEmpty()) {
                    md.append("**Fields**\n\n");
                    entity.getFields().forEach(f -> md.append("- `").append(f).append("`\n"));
                    md.append("\n");
                }
                if (entity.getRelationships() != null && !entity.getRelationships().isEmpty()) {
                    md.append("**Relationships**\n\n");
                    entity.getRelationships().forEach(r -> md.append("- ").append(r).append("\n"));
                    md.append("\n");
                }
            });
        }

        // Config changes
        if (sol.getArchitectureDetail() != null
                && sol.getArchitectureDetail().getConfigChanges() != null
                && !sol.getArchitectureDetail().getConfigChanges().isEmpty()) {
            md.append("## Configuration Changes\n\n")
              .append("| Key | Value | Description |\n")
              .append("|-----|-------|-------------|\n");
            sol.getArchitectureDetail().getConfigChanges().forEach(cfg ->
                md.append("| `").append(cfg.getKey()).append("` | `")
                  .append(cfg.getValue()).append("` | ")
                  .append(cfg.getDescription()).append(" |\n"));
            md.append("\n");
        }

        // Reusable services
        if (sol.getReusableServices() != null && !sol.getReusableServices().isEmpty()) {
            md.append("## Reusable Services\n\n");
            md.append("> These services already exist in the codebase — use them rather than "
                    + "building from scratch.\n\n");
            sol.getReusableServices().forEach(svc -> {
                md.append("### ").append(svc.getServiceName()).append("\n\n");
                if (svc.getFilePath() != null) {
                    md.append("**File**: `").append(svc.getFilePath()).append("`\n\n");
                }
                if (svc.getDescription() != null) {
                    md.append(svc.getDescription()).append("\n\n");
                }
                if (svc.getImportStatement() != null) {
                    md.append("**Import / Inject**\n\n```\n")
                      .append(svc.getImportStatement()).append("\n```\n\n");
                }
                if (svc.getMethodsToCall() != null && !svc.getMethodsToCall().isEmpty()) {
                    md.append("**Methods to call**\n\n");
                    svc.getMethodsToCall().forEach(m -> md.append("- `").append(m).append("`\n"));
                    md.append("\n");
                }
                if (svc.getHowToUse() != null) {
                    md.append("**How to use**\n\n").append(svc.getHowToUse()).append("\n\n");
                }
            });
        }

        // Recommended libraries
        if (sol.getRecommendedLibraries() != null && !sol.getRecommendedLibraries().isEmpty()) {
            md.append("## Recommended Libraries\n\n")
              .append("| Library | Version | Purpose | Already in project |\n")
              .append("|---------|---------|---------|--------------------|\n");
            sol.getRecommendedLibraries().forEach(lib -> {
                String inProject = Boolean.TRUE.equals(lib.getAlreadyInProject()) ? "✅ Yes" : "No";
                String docLink = lib.getDocumentationUrl() != null && !lib.getDocumentationUrl().isBlank()
                    ? "[docs](" + lib.getDocumentationUrl() + ")" : "—";
                md.append("| **").append(lib.getName()).append("** ")
                  .append(docLink).append(" | ")
                  .append(lib.getVersion() != null ? lib.getVersion() : "—").append(" | ")
                  .append(lib.getPurpose()).append(" | ")
                  .append(inProject).append(" |\n");
            });
            md.append("\n");
        }

        // Implementation steps
        if (sol.getImplementationSteps() != null && !sol.getImplementationSteps().isEmpty()) {
            md.append("## Implementation Steps\n\n");
            int total = sol.getImplementationSteps().stream()
                .mapToInt(s -> s.getEstimatedHours() != null ? s.getEstimatedHours() : 0)
                .sum();
            md.append("**Total estimated effort**: ").append(total).append("h\n\n");

            sol.getImplementationSteps().forEach(step -> {
                md.append("### Step ").append(step.getStepNumber())
                  .append(": ").append(step.getTitle()).append("\n\n");
                md.append("**Estimated**: ")
                  .append(step.getEstimatedHours() != null ? step.getEstimatedHours() : "?")
                  .append("h\n\n");
                if (step.getDependsOnSteps() != null && !step.getDependsOnSteps().isEmpty()) {
                    String deps = step.getDependsOnSteps().stream()
                        .map(d -> "Step " + d)
                        .collect(Collectors.joining(", "));
                    md.append("**Depends on**: ").append(deps).append("\n\n");
                }
                if (step.getDescription() != null && !step.getDescription().isBlank()) {
                    md.append(step.getDescription()).append("\n\n");
                }
                if (step.getFilesToCreate() != null && !step.getFilesToCreate().isEmpty()) {
                    md.append("**Files to create** (+)\n\n");
                    step.getFilesToCreate().forEach(f -> md.append("- `").append(f).append("`\n"));
                    md.append("\n");
                }
                if (step.getFilesToModify() != null && !step.getFilesToModify().isEmpty()) {
                    md.append("**Files to modify** (~)\n\n");
                    step.getFilesToModify().forEach(f -> md.append("- `").append(f).append("`\n"));
                    md.append("\n");
                }
                if (step.getMethodSignatures() != null && !step.getMethodSignatures().isEmpty()) {
                    md.append("**Method signatures to implement**\n\n```\n");
                    step.getMethodSignatures().forEach(sig -> md.append(sig).append("\n"));
                    md.append("```\n\n");
                }
                if (step.getSubTasks() != null && !step.getSubTasks().isEmpty()) {
                    md.append("**Sub-tasks**\n\n");
                    step.getSubTasks().forEach(sub -> {
                        md.append("- [ ] ").append(sub.getTask()).append("\n");
                        if (sub.getAcceptanceCriteria() != null
                                && !sub.getAcceptanceCriteria().isBlank()) {
                            md.append("  - *Acceptance*: ").append(sub.getAcceptanceCriteria())
                              .append("\n");
                        }
                    });
                    md.append("\n");
                }
            });
        }

        // Risk factors
        if (sol.getRiskFactors() != null && !sol.getRiskFactors().isEmpty()) {
            md.append("## Risk Factors\n\n");
            sol.getRiskFactors().forEach(r -> md.append("- ⚠️ ").append(r).append("\n"));
            md.append("\n");
        }

        // Best practices
        if (sol.getBestPractices() != null && !sol.getBestPractices().isEmpty()) {
            md.append("## Best Practices\n\n");
            sol.getBestPractices().forEach(bp -> md.append("- ").append(bp).append("\n"));
            md.append("\n");
        }

        String category = stackCategory(stack);
        return GeneratedMarkdownFile.builder()
            .filename(stackGuideFilename(stack))
            .title(stack.getDisplayName() + " Implementation Guide")
            .content(md.toString())
            .category(category)
            .stackType(stack)
            .build();
    }

    /**
     * Builds a consolidated API design file from all stacks.
     * Returns null if no stack has any API contracts.
     */
    private GeneratedMarkdownFile buildApiDesignFile(
            WiseArchitectureResponseDTO r, Pitch pitch) {

        boolean hasAnyContracts = r.getSolutions().values().stream()
            .anyMatch(sol -> sol.getArchitectureDetail() != null
                && sol.getArchitectureDetail().getApiContracts() != null
                && !sol.getArchitectureDetail().getApiContracts().isEmpty());

        if (!hasAnyContracts) {
            return null;
        }

        StringBuilder md = new StringBuilder();
        md.append("# API Design Guide\n\n");
        md.append("> **Pitch**: ").append(pitch.getTitle()).append("\n\n");
        md.append("> This document consolidates all API contracts across technology stacks. "
                + "It is the authoritative reference for integration between client and server.\n\n");

        // Summary table
        md.append("## Endpoint Summary\n\n")
          .append("| Method | Endpoint | Stack | Description |\n")
          .append("|--------|----------|-------|-------------|\n");

        r.getSolutions().forEach((stack, sol) -> {
            if (sol.getArchitectureDetail() == null
                    || sol.getArchitectureDetail().getApiContracts() == null) {
                return;
            }
            sol.getArchitectureDetail().getApiContracts().forEach(api ->
                md.append("| `").append(api.getMethod()).append("` | `")
                  .append(api.getEndpoint()).append("` | ")
                  .append(stack.getDisplayName()).append(" | ")
                  .append(api.getDescription()).append(" |\n"));
        });
        md.append("\n");

        // Detailed per-stack contracts
        r.getSolutions().forEach((stack, sol) -> {
            if (sol.getArchitectureDetail() == null
                    || sol.getArchitectureDetail().getApiContracts() == null
                    || sol.getArchitectureDetail().getApiContracts().isEmpty()) {
                return;
            }
            md.append("## ").append(stack.getDisplayName()).append(" APIs\n\n");
            sol.getArchitectureDetail().getApiContracts().forEach(api -> {
                md.append("### `").append(api.getMethod()).append(" ").append(api.getEndpoint())
                  .append("`\n\n");
                if (api.getDescription() != null) {
                    md.append(api.getDescription()).append("\n\n");
                }
                if (api.getRequestShape() != null && !api.getRequestShape().isBlank()) {
                    md.append("**Request**\n\n```json\n")
                      .append(api.getRequestShape()).append("\n```\n\n");
                }
                if (api.getResponseShape() != null && !api.getResponseShape().isBlank()) {
                    md.append("**Response**\n\n```json\n")
                      .append(api.getResponseShape()).append("\n```\n\n");
                }
            });
        });

        return GeneratedMarkdownFile.builder()
            .filename("api-design.md")
            .title("API Design Guide")
            .content(md.toString())
            .category("api")
            .stackType(null)
            .build();
    }

    private GeneratedMarkdownFile buildImplementationPlanFile(
            WiseArchitectureResponseDTO r, Pitch pitch) {

        StringBuilder md = new StringBuilder();
        md.append("# Implementation Plan\n\n");
        md.append("> **Pitch**: ").append(pitch.getTitle()).append("\n\n");
        md.append("> Follow steps in the order listed. Steps within a phase can be parallelised "
                + "where dependency constraints allow.\n\n");

        // Summary
        int totalHours = r.getSolutions().values().stream()
            .mapToInt(sol -> sol.getEstimatedHours() != null ? sol.getEstimatedHours() : 0)
            .sum();
        int weeks = (int) Math.ceil(totalHours / 40.0);
        md.append("**Total effort**: ~").append(totalHours).append("h (~")
          .append(weeks).append(" engineer-week").append(weeks == 1 ? "" : "s").append(")\n\n");

        md.append("| Phase | Stack | Steps | Estimated |\n")
          .append("|-------|-------|-------|----------|\n");
        int[] phaseNum = {1};
        r.getSolutions().forEach((stack, sol) -> {
            int stepCount = sol.getImplementationSteps() != null
                ? sol.getImplementationSteps().size() : 0;
            md.append("| Phase ").append(phaseNum[0]++).append(" | ")
              .append(stack.getDisplayName()).append(" | ")
              .append(stepCount).append(" steps | ")
              .append(sol.getEstimatedHours() != null ? sol.getEstimatedHours() + "h" : "—")
              .append(" |\n");
        });
        md.append("\n");

        // Per-phase steps
        int[] phase = {1};
        r.getSolutions().forEach((stack, sol) -> {
            md.append("## Phase ").append(phase[0]++).append(": ")
              .append(stack.getDisplayName()).append("\n\n");

            if (sol.getImplementationSteps() == null || sol.getImplementationSteps().isEmpty()) {
                md.append("_No implementation steps generated for this stack._\n\n");
                return;
            }

            sol.getImplementationSteps().forEach(step -> {
                md.append("### Step ").append(step.getStepNumber())
                  .append(": ").append(step.getTitle())
                  .append(" (").append(step.getEstimatedHours() != null
                        ? step.getEstimatedHours() : "?").append("h)\n\n");

                if (step.getDependsOnSteps() != null && !step.getDependsOnSteps().isEmpty()) {
                    String deps = step.getDependsOnSteps().stream()
                        .map(d -> "Step " + d)
                        .collect(Collectors.joining(", "));
                    md.append("_Depends on_: ").append(deps).append("\n\n");
                }

                if (step.getDescription() != null && !step.getDescription().isBlank()) {
                    md.append(step.getDescription()).append("\n\n");
                }

                if (step.getSubTasks() != null && !step.getSubTasks().isEmpty()) {
                    step.getSubTasks().forEach(sub ->
                        md.append("- [ ] ").append(sub.getTask()).append("\n"));
                    md.append("\n");
                }
            });
        });

        // Reduced scope note
        if (r.getReducedScope() != null) {
            md.append("## Reduced Scope (Appetite Exceeded)\n\n")
              .append(r.getReducedScope().getExplanation()).append("\n\n");
            if (r.getReducedScope().getDeferredItems() != null) {
                md.append("**Deferred to later release:**\n\n");
                r.getReducedScope().getDeferredItems().forEach(item ->
                    md.append("- ").append(item).append("\n"));
                md.append("\n");
            }
        }

        return GeneratedMarkdownFile.builder()
            .filename("implementation-plan.md")
            .title("Implementation Plan")
            .content(md.toString())
            .category("plan")
            .stackType(null)
            .build();
    }

    // ──────────────────────────────────────────────────────────────────────────────────────────────
    // Helpers
    // ──────────────────────────────────────────────────────────────────────────────────────────────

    private static String stackGuideFilename(TechStackType stack) {
        return stack.getIdentifier() + "-implementation-guide.md";
    }

    private static String stackCategory(TechStackType stack) {
        return switch (stack.getCategory()) {
            case "MOBILE" -> "mobile";
            case "BACKEND" -> "backend";
            case "WEB" -> "web";
            default -> "overview";
        };
    }
}
