package com.github.farzadsedaghatbin.shipflow.dto.wisearchitecture;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a single Markdown file generated by Wise Architecture.
 * Multiple files are generated per analysis (one per stack + cross-stack guides).
 * These files are intended to be consumed directly by AI coding agents (Claude Code,
 * Cursor, GitHub Copilot, etc.) to drive implementation of the pitch.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GeneratedMarkdownFile {

    /**
     * Filesystem-safe filename including .md extension.
     * Examples: "architecture-overview.md", "java-spring-implementation-guide.md",
     *           "api-design.md", "implementation-plan.md"
     */
    private String filename;

    /**
     * Human-readable title for the file.
     * Example: "Architecture Overview", "Java (Spring) Implementation Guide"
     */
    private String title;

    /**
     * Full Markdown content ready to write to disk or display in a viewer.
     */
    private String content;

    /**
     * Logical category used for UI grouping and icon selection.
     * Values: "overview", "backend", "mobile", "web", "api", "plan"
     */
    private String category;

    /**
     * Stack type this file describes, null for cross-stack files
     * (overview, api-design, implementation-plan).
     */
    private TechStackType stackType;
}
